### ISSUE TITLE
are there more contributions to the handbook?

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-602#13]
Just to verify. Are there more contributions to the handbook?

Link is posted in class piazza

**Comment by Keerthi4308** [comment]
> Just to verify. Are there more contributions to the handbook?
> 
> Link is posted in class piazza

I contributed to paper, project and a tutorial for raspberry pi only.

**Comment by Keerthi4308** [comment]
If that's okay, please  allow me to close the issue
