### ISSUE TITLE
outdated code

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-602#14]
| cloudmesh-community/hid-sp18-602
-- | --
Known moderate severity security vulnerability detected in flask < 0.12.3defined in requirements.txt.requirements.txt update suggested: flask ~> 0.12.3.Always verify the validity and compatibility of suggestions with your codebase. | Known moderate severity security vulnerability detected in flask < 0.12.3defined in requirements.txt. | requirements.txt update suggested: flask ~> 0.12.3. | Always verify the validity and compatibility of suggestions with your codebase.
Known moderate severity security vulnerability detected in flask < 0.12.3defined in requirements.txt.
requirements.txt update suggested: flask ~> 0.12.3.
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by Keerthi4308** [comment]
Go rid of the versions in requirements.txt in my latest update
