### ISSUE TITLE
Deploy application on AWS

### ISSUE THREAD

**Issue by Keerthi4308** [cloudmesh-community/hid-sp18-602#16]
Understand how to do it then you might need to write a script to deploy the application on aws as well as gcp

**Comment by comradelemoncake** [comment]
I have some suggestions for this if you're open to assistance...

**Comment by Keerthi4308** [comment]
> I have some suggestions for this if you're open to assistance...

Sure, definitely!!

**Comment by Keerthi4308** [comment]
Done
