### ISSUE TITLE
paper: convert to md

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-602#7]
https://github.com/cloudmesh-community/hid-sp18-602/blob/master/paper/content.tex
convert to md
follow our instructions we gave in class this semester
paper.md
paper.bib

spaces missing after colon, citation missing after technology
we have not done full review yet as that will happen when you submit as final

you must watch the epub with the papers included to make sure it shows up right, but we can not do this till you have not converted to md

its trivial, use our sample as posted to the class

**Comment by laszewsk** [comment]
done by Gregors, its now in the book. However, we noticed that it does not include a real example. Will you add one or not? I am just curious

**Comment by Keerthi4308** [comment]
Thank you so much for the support.   Also, I have already included a paragraph about where and how CloudAutoml is currently being used. Is that what are you are suggesting "by real example ". Anyway, I'm checking handbook, so I will get back to you if I have questions.
